### ISSUE TITLE
component props update problem

### ISSUE THREAD

**Issue by indatawetrust** [cx690/react-loadable#2]
component props cannot be updated due to the following line. i fixed the problem with [this pr](https://github.com/cx690/react-loadable/pull/1)

https://github.com/cx690/react-loadable/blob/main/src/index.tsx#L151

**Comment by indatawetrust** [comment]
https://github.com/cx690/react-loadable/pull/1

**Comment by cx690** [comment]
fixed it at version 1.1.2

**Comment by cx690** [comment]
Thanks a lot!
